_wandb:
    value:
        cli_version: 0.23.1
        e:
            vp4xd8ch48objbid8k1fc6hnwfuyf8e0:
                email: alexjacob260@gmail.com
                executable: /Users/jacob/courses/SMIT-AI-B4/dl/Desi-Food-Classifier-CNN/.venv/bin/python3
                git:
                    commit: e6dd00fab3b1a687ca888b4b386dc6837a244df6
                    remote: https://github.com/AshleyAlexJacob/Desi-Food-Classifier-CNN.git
                host: JACOBs-MacBook-Air.local
                os: macOS-26.0.1-arm64-arm-64bit
                program: -m src.pipelines.model_training
                python: CPython 3.10.6
                root: /Users/jacob/courses/SMIT-AI-B4/dl/Desi-Food-Classifier-CNN
                startedAt: "2026-01-11T12:28:42.207094Z"
                writerId: vp4xd8ch48objbid8k1fc6hnwfuyf8e0
        m: []
        python_version: 3.10.6
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.10.6
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
Batch Size:
    value: 32
Device:
    value: cpu
Epochs:
    value: 100
Learning Rate:
    value: 0.001
Model:
    value: src.model.cnn.CNN
